name: API Tests - Pytest

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install json-server
        run: npm install -g json-server

      - name: Start json-server
        run: |
          json-server --watch db.json --port 3000 &
          sleep 5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          BASE_URL: http://localhost:3000
        run: pytest -v